site_name: WLAN Pi Web GUI
nav:
    - Speedtest:
        - Classic: index.md
        - Graph: speedtestgraph.md
    - Downloads: utilities.md
    - Profiler: profiler.md
    - Admin Panel (Cockpit): cockpit.md
    - Documentation: documentation.md
    - About: about.md
theme:
    name: 'material'
    icon:
        logo: material/wifi
    language: en
extra_css:
  - extra.css
markdown_extensions:
  - admonition
plugins:
    - search
dev_addr: '127.0.0.1:8880'

